CREATE USER meditriage IDENTIFIED BY med123;
GRANT CONNECT, RESOURCE TO meditriage;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.PATIENT TO meditriage;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.PATIENT_PHONE TO meditriage;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.DOCTOR TO meditriage;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.DOCTOR_PHONE TO meditriage;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.TRIAGE_SESSION TO meditriage;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.SYMPTOM TO meditriage;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.SESSION_SYMPTOM TO meditriage;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.AI_DIAGNOSIS TO meditriage;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.PATIENT_HISTORY TO meditriage;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.HISTORY_SYMPTOM_SUMMARY TO meditriage;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.AUDIT_LOG TO meditriage;
GRANT UNLIMITED TABLESPACE TO meditriage;




CREATE SYNONYM meditriage.PATIENT FOR SYSTEM.PATIENT;
CREATE SYNONYM meditriage.PATIENT_PHONE FOR SYSTEM.PATIENT_PHONE;
CREATE SYNONYM meditriage.DOCTOR FOR SYSTEM.DOCTOR;
CREATE SYNONYM meditriage.DOCTOR_PHONE FOR SYSTEM.DOCTOR_PHONE;
CREATE SYNONYM meditriage.TRIAGE_SESSION FOR SYSTEM.TRIAGE_SESSION;
CREATE SYNONYM meditriage.SYMPTOM FOR SYSTEM.SYMPTOM;
CREATE SYNONYM meditriage.SESSION_SYMPTOM FOR SYSTEM.SESSION_SYMPTOM;
CREATE SYNONYM meditriage.AI_DIAGNOSIS FOR SYSTEM.AI_DIAGNOSIS;
CREATE SYNONYM meditriage.PATIENT_HISTORY FOR SYSTEM.PATIENT_HISTORY;
CREATE SYNONYM meditriage.HISTORY_SYMPTOM_SUMMARY FOR SYSTEM.HISTORY_SYMPTOM_SUMMARY;
CREATE SYNONYM meditriage.AUDIT_LOG FOR SYSTEM.AUDIT_LOG;  
ALTER USER meditriage IDENTIFIED BY med123;
ALTER USER meditriage IDENTIFIED BY med123;
SELECT username, account_status FROM dba_users WHERE username = 'MEDITRIAGE';
SELECT * FROM v$version WHERE ROWNUM = 1;
SELECT username, account_status, con_id 
FROM cdb_users 
WHERE username = 'MEDITRIAGE';
SELECT * FROM SYSTEM.PATIENT ORDER BY patient_id DESC
;
SELECT * FROM SYSTEM.PATIENT;
SELECT * FROM SYSTEM.PATIENT_phone;
SELECT * FROM SYSTEM.DOCTOR;
SELECT * FROM SYSTEM.TRIAGE_SESSION;
SELECT * FROM SYSTEM.AI_DIAGNOSIS;
SELECT * FROM SYSTEM.HISTORY_SYMPTOM_SUMMARY;
SELECT * FROM SYSTEM.audit_log;
SELECT * FROM SYSTEM.patient_history;
drop table history_symptom_summary;



